// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gobbezdstkpaciwcvpjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvYmJlemRzdGtwYWNpd2N2cGpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MTMzODYsImV4cCI6MjA2NjI4OTM4Nn0.8GKs35NqWTWEa5k1BzKt-pNrG36LNd1M47M4J85cY-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);